name: Playwright BDD Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: "30 4  * * *"   # 10:00 AM IST daily

jobs:

  test:
    runs-on: ubuntu-latest

    env:
      ENV: qa
      BASE_URL: ${{ secrets.BASE_URL }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      BROWSER: ${{ secrets.BROWSER }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Tests
        run: npm test || true

      - name: Generate Allure Report
        run: npm run allure:generate || true

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          if-no-files-found: ignore

      # 📧 Send Email Notification
      - name: Send Email with Allure Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}

          subject: "Playwright Automation Report - Run #${{ github.run_number }}"
          to: ${{ secrets.EMAIL_TO }}
          from: "Automation CI <${{ secrets.SMTP_USER }}>"

          body: |
            Hello,

            Playwright automation execution completed.

            Repository: ${{ github.repository }}
            Run Number: ${{ github.run_number }}

            Download Allure Report:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Regards,
            Automation CI

          attachments: allure-report/index.html